### PR TITLE
Update 0001-bep-template.md

### PR DESCRIPTION
**Pull request by MicDr**
This update is a result of [this](https://bonsai.groups.io/g/main/topic/bep0001_community/30394665?p=,,,20,0,0,0::recentpostdate%2Fsticky,,,20,2,0,30394665) ongoing discussion

Pinging @cmutel or @romainsacchi for merging

### CODE REVIEW

**Comment by cmutel** [comment]
👍, though I suggested a few language changes in a PR.

**Comment by MicDr** [comment]
True, the third bullet point was the object of your language change request and I have changed it. 
Did I miss something?

**Comment by romainsacchi** [comment]
@MicDr  there's a pending PR about a commit from Chris to your version of the file. See [here](https://github.com/BONSAMURAIS/enhancements/pull/8/commits/156331b84304186b4d9cde4d8c4f8eb85a09c254).
 Maybe you should accept that one first before bringing your changes into the master branch version.

**Comment by MicDr** [comment]
Thanks @romainsacchi, missed it. Approved!

**Pull request merged**
